apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesla-clone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tesla-clone
  template:
    metadata:
      labels:
        app: tesla-clone
    spec:
      containers:
      - name: tesla-clone
        image: tesla-clone:21
        ports:
        - containerPort: 9005

---
apiVersion: v1
kind: Service
metadata:
  name: tesla-clone-service
spec:
  type: LoadBalancer
  selector:
    app: tesla-clone
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tesla-clone-ingress
spec:
  rules:
  - host: tesla-clone.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tesla-clone-service
            port:
              number: 80
