apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesla-clone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tesla-clone
  template:
    metadata:
      labels:
        app: tesla-clone
    spec:
      containers:
      - name: tesla-clone
        image: mohsin01/tesla-clone:21
        ports:
        - containerPort: 9005

---
apiVersion: v1
kind: Service
metadata:
  name: tesla-clone-service
spec:
  type: LoadBalancer
  selector:
    app: tesla-clone
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9005

